version: "3"

services:
  database:
    container_name: 42stats-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - 42stats_network
    restart: always

  app:
    container_name: 42stats-app
    image: 42stats-app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FORTY_TWO_UID: ${FORTY_TWO_UID}
      FORTY_TWO_SECRET: ${FORTY_TWO_SECRET}
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - 42stats_network
    restart: always

  tasks:
    container_name: 42stats-tasks
    image: 42stats-tasks
    build:
      context: ./tasks
      dockerfile: Dockerfile
    depends_on:
      - app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FORTY_TWO_UID: ${FORTY_TWO_UID}
      FORTY_TWO_SECRET: ${FORTY_TWO_SECRET}
    networks:
      - 42stats_network
    restart: always

networks:
  42stats_network:
    name: 42stats_network

volumes:
  database:
